// Cloudflare Worker entry point. Serves the Next.js app (built by OpenNext)
// and runs the hourly cron that sends learners their daily practice texts.
// @ts-ignore -- generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";

export default {
  fetch: handler.fetch,

  async scheduled(_event: ScheduledController, env: CloudflareEnv, ctx: ExecutionContext) {
    // Route through the app so the request has the usual Next.js context.
    const request = new Request("https://cron.internal/api/cron/proactive", {
      headers: { authorization: `Bearer ${env.CRON_SECRET}` },
    });
    ctx.waitUntil(
      handler.fetch(request, env, ctx).then(async (res: Response) => {
        console.log("practice texts cron", res.status, await res.text());
      }),
    );
  },
} satisfies ExportedHandler<CloudflareEnv>;
